services:
  qwen:
    build:
      context: .
      dockerfile: docker/Dockerfile.qwen
    container_name: qwen
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - VLLM_LOGGING_LEVEL=INFO
